const GENERAL_TYPES = {
    SET_SHOW_NAVBAR: 'SET_SHOW_NAVBAR',
    SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
    SET_AUTHORIZED: 'SET_AUTHORIZED',
    CLEAR_AUTHORIZATION: 'CLEAR_AUTHORIZATION',
    SET_SELECTED_CUSTOMER_TAB: 'SET_SELECTED_CUSTOMER_TAB',
    SET_LAST_ROUTE_BEFORE_AUTH: 'SET_LAST_PAGE_BEFORE_AUTH'
}

export default GENERAL_TYPES