const GENERAL_TYPES = {
    SET_SHOW_NAVBAR: 'SET_SHOW_NAVBAR',
    SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
    SET_AUTHORIZED: 'SET_AUTHORIZED',
    CLEAR_AUTHORIZATION: 'CLEAR_AUTHORIZATION'
}

export default GENERAL_TYPES