const CART_TYPES = {
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    DELETE_CART_ITEM: "DELETE_CART_ITEM",
    CLEAR_CART: "CLEAR_CART",
    SAVE_CART: "SAVE_CART"
}

export default CART_TYPES